Homework04
I-Solodukhina/Hillel-Home-Works pull request #3
Opened 2024-06-30 17:40 UTC by I-Solodukhina

2024-06-30 21:12 UTC, qavitalii requested changes

2024-06-30 21:12 UTC, qavitalii commented on lesson_04/homework_04.py
> +def count_capitalized_words(text):
Розмію, поки що ми ще не проходили функції. Але оскільки вже ви їх використали то зауважу, що аргемент text тут не потрібний. Бо ваша функція його ніде в тілі не використовує.

2024-06-30 21:12 UTC, qavitalii commented on lesson_04/homework_04.py
> +
Тут не вірно. 
Можете спробувати відтворити. Змінивши речення типу ось так "Ben was fagged out, !!! By the time !!! Tom had traded the next chance to Billy Fisher for" ( знаки !!! простов використав для того щоб виділити фразу)

Ваш код, теж скаже що це речення починається з "By the time" 

![image](https://github.com/I-Solodukhina/Hillel-Home-Works/assets/64067815/8d9d9bc8-5852-43fa-8a22-bfd63a4bee33)

Вам слід використати НЕ конструкцію if "By the time" in .....:
Спробуйте подивитися у напрямку .startswith

2024-07-01 09:32 UTC, I-Solodukhina commented on lesson_04/homework_04.py
> +def count_capitalized_words(text):
Параметр text тут потрібний, бо я використовую функцію з аргументом у print, інакше виникає помилка
![2024-07-01_12h29_32](https://github.com/I-Solodukhina/Hillel-Home-Works/assets/126875218/46370ecf-04ff-4028-a4cf-84d120a63c05)

2024-07-01 09:54 UTC, I-Solodukhina commented on lesson_04/homework_04.py
> +def count_capitalized_words(text):
все, зрозуміла що не так - виправила

2024-07-01 09:57 UTC, I-Solodukhina commented on lesson_04/homework_04.py
> +
Виправлено

2024-07-01 10:07 UTC, qavitalii approved these changes

2024-07-01 10:08 UTC, merged